version: '3'
services:
   consignment-service:
    build: ..
    volumes:
      - ./consignment-service:/app
    ports:
      - "50001:50001"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: mdns